version: "3"

services:

  app:
    container_name: scraper
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
    environment: 
      ELASTIC_DB_HOST_NAME: elasticsearch
      TOR_PROXY_HOST_NAME: tor
      CSV_PATH: app/app/articles.csv
    volumes:
      - type: bind
        source: ./app
        target: /app/app
    command: sh -c '/app/app/wait_for_it.sh elasticsearch:9200 && /app/app/wait_for_it.sh tor:9050 && python app/app/scraper.py'

    networks:
      frontapp_a:
        ipv4_address: 172.22.0.11
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
    networks:
      frontapp_a:
        ipv4_address: 172.22.0.10

  tor:
    container_name: tor
    image: dperson/torproxy
    hostname: tor
    restart: unless-stopped
    ports:
      - 9050:9050
    networks:
      frontapp_a:
        ipv4_address: 172.22.0.12

  node:
    container_name: node
    build:
      context: "."
      dockerfile: Dockerfile.node
    ports:
      - "8080:8080"
    volumes:
      - ./node:/app
      - /app/node_modules/
    command: sh -c '/opt/wait_for_it.sh elasticsearch:9200 && cd server && node .'
    environment:
      - ELASTIC_DB_HOST_NAME=elasticsearch
      - API_HOST_NAME=api
      - MONGODB_URI=mongodb+srv://klessliam:1oKhEQro3BvH1NqE@cluster0.ixnea.mongodb.net/<dbname>?retryWrites=true&w=majority

    networks:
      frontapp_a:
        ipv4_address: 172.22.0.13
    depends_on:
      - elasticsearch

  alerts:
    container_name: alerts
    build:
      context: "."
      dockerfile: Dockerfile.alerts
    ports:
      - "8081:8081"
    volumes:
      - ./alerts:/app
      - /app/node_modules/
    command: sh -c '/opt/wait_for_it.sh elasticsearch:9200 && node .'
    environment:
      - ELASTIC_DB_HOST_NAME=elasticsearch
      - API_HOST_NAME=api
      - MONGODB_URI=mongodb+srv://klessliam:1oKhEQro3BvH1NqE@cluster0.ixnea.mongodb.net/<dbname>?retryWrites=true&w=majority
    networks:
      frontapp_a:
        ipv4_address: 172.22.0.14
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local

networks:
  frontapp_a:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
  elastic:
    driver: bridge